### ISSUE TITLE
DB Username and password are currently hard coded

### ISSUE THREAD

**Issue by samredway** [Shades-2/cleaner-app#1]
DB username and password should be pulled in from the local environment so that they are not hard coded in the app.py file. 

- step one make user/password be pulled in from local env using os.environ 
- step two use dotenv so user can create a local .env file
- add .env file to gitignore as this will not be pushed to repo
- add note to README.md so user understands how to set up user pass and db using docker (the readme should have the command to pull and run the postgrese image as well as a note on how to set up teh user name pass config)

**Comment by Shades-2** [comment]
Done
